server:
  port: 8889
spring:
  application:
    name: consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.xt.open.jmall.product.remote.feignclients.CartFeignClient: debug
