server:
  port: 8888
spring:
  application:
    name: consumer
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.xt.open.jmall.product.remote.feignclients.CartFeignClient: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
# 开启熔断
feign:
  hystrix:
    enabled: true